name: Playwright Report

on:
  push:
    branches: [feature/pocket-base-bdd]
  pull_request:
    branches: [feature/pocket-base-bdd]
  workflow_dispatch:

jobs:
  test-and-deploy:
    timeout-minutes: 60
    environment: Production
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      USER_NAME: ${{ vars.USER_NAME }}
      PASSWORD: ${{ vars.PASSWORD }}
      INVALID_USER_NAME: ${{ vars.INVALID_USER_NAME }}
      INVALID_PASSWORD: ${{ vars.INVALID_PASSWORD }}
      BASE_URL: ${{ vars.BASE_URL }}
      CI: ${{ vars.CI }}
    defaults:
      run:
        working-directory: ./PocketBase

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: ./PocketBase/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm ci

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright BDD tests
        run: pnpm test

      - name: Upload artifact reports
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: ./PocketBase/deploy-report/
          retention-days: 30

      - name: Install Vercel
        run: pnpm install -g vercel

      - name: Deploy Report to Vercel
        run: vercel --prod --cwd=deploy-report --token=${{ secrets.VERCEL_TOKEN }} --yes
