name: Playwright Report

on:
  push:
    branches: [feature/pocket-base]
  pull_request:
    branches: [feature/pocket-base]

jobs:
  test-and-deploy:
    timeout-minutes: 60
    environment: Production
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      USER_NAME: ${{ vars.USER_NAME }}
      PASSWORD: ${{ vars.PASSWORD }}
      INVALID_USER_NAME: ${{ vars.INVALID_USER_NAME }}
      INVALID_PASSWORD: ${{ vars.INVALID_PASSWORD }}
      BASE_URL: ${{ vars.BASE_URL }}
    defaults:
      run:
        working-directory: ./PocketBase
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./PocketBase/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_USER_NAME: ${{ vars.USER_NAME }}
          envkey_PASSWORD: ${{ vars.PASSWORD }}
          envkey_INVALID_USER_NAME: ${{ vars.INVALID_USER_NAME }}
          envkey_INVALID_PASSWORD: ${{ vars.INVALID_PASSWORD }}
          envkey_BASE_URL: ${{ vars.BASE_URL }}
          directory: ./PocketBase
          file_name: .env

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload artifact playwright-report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Install vercel
        run: npm install -g vercel

      - name: Deploy Playwright Report to Vercel
        run: vercel --prod --cwd=playwright-report --token=${{ secrets.VERCEL_TOKEN }} --yes
